//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TRUNG;Initial Catalog=Hanoiguesthouses;User ID=sa;Password=123456789")]
        public string HanoiguesthousesConnectionString {
            get {
                return ((string)(this["HanoiguesthousesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=TeamplateHotel;User ID=sa;Password=1234567" +
            "")]
        public string HanoiCityHotelConnectionString {
            get {
                return ((string)(this["HanoiCityHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=HaNoiCityPlaceHotel;Persist Security Info=" +
            "True;User ID=sa;Password=1234567")]
        public string HaNoiCityPlaceHotelConnectionString {
            get {
                return ((string)(this["HaNoiCityPlaceHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=EssenceHanoi;User ID=sa;Password=1234567")]
        public string EssenceHanoiConnectionString {
            get {
                return ((string)(this["EssenceHanoiConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUNG-PC\\MANH;Initial Catalog=TeamplateHotel_25082014;User ID=sa;Passw" +
            "ord=123456")]
        public string TeamplateHotel_25082014ConnectionString {
            get {
                return ((string)(this["TeamplateHotel_25082014ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUNG-PC\\MANH;Initial Catalog=TeamplateHotel;User ID=sa;Password=12345" +
            "6")]
        public string TeamplateHotelConnectionString {
            get {
                return ((string)(this["TeamplateHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=TestTeamplateHotel;User ID=sa;Password=123" +
            "4567")]
        public string TestTeamplateHotelConnectionString {
            get {
                return ((string)(this["TestTeamplateHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=TeamplateHotel29112014;User ID=sa;Password" +
            "=1234567")]
        public string TeamplateHotel29112014ConnectionString {
            get {
                return ((string)(this["TeamplateHotel29112014ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VENUSMEDIA;Initial Catalog=DbTestTeamplateHotel;User ID=sa;Password=1" +
            "234567")]
        public string DbTestTeamplateHotelConnectionString {
            get {
                return ((string)(this["DbTestTeamplateHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC\\WEBHOTEL;Initial Catalog=DemoWebhotel;Integrated Securit" +
            "y=True")]
        public string DemoWebhotelConnectionString {
            get {
                return ((string)(this["DemoWebhotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.27.60.26;Initial Catalog=DemoWebhotel;User ID=DemoWebhotel;Passwo" +
            "rd=DemoWebhotel@123465")]
        public string DemoWebhotelConnectionString1 {
            get {
                return ((string)(this["DemoWebhotelConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC-PC\\CMLVIETNAM;Initial Catalog=BienBachotel;User ID=sa;Pa" +
            "ssword=abc@123")]
        public string BienBachotelConnectionString {
            get {
                return ((string)(this["BienBachotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC-PC\\CMLVIETNAM;Initial Catalog=TeamplateHotel_NoBe;User I" +
            "D=sa;Password=abc@123")]
        public string TeamplateHotel_NoBeConnectionString {
            get {
                return ((string)(this["TeamplateHotel_NoBeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC-PC\\CML_SERVER;Initial Catalog=TeamplateHotel_NoBE;User I" +
            "D=sa;Password=abc@123")]
        public string TeamplateHotel_NoBEConnectionString1 {
            get {
                return ((string)(this["TeamplateHotel_NoBEConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHONGLUIBUOC-PC\\CML_SERVER;Initial Catalog=ASIKY;User ID=sa;Password=" +
            "abc@123")]
        public string ASIKYConnectionString {
            get {
                return ((string)(this["ASIKYConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHAMPHUONG-PC\\SQLEXPRESS;Initial Catalog=ASIKY;Persist Security Info=" +
            "True;User ID=sa;Password=123456")]
        public string ASIKYConnectionString1 {
            get {
                return ((string)(this["ASIKYConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-D0LSMIU\\SQLEXPRESS;Initial Catalog=ASIKY;Integrated Security=" +
            "True")]
        public string ASIKYConnectionString2 {
            get {
                return ((string)(this["ASIKYConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-D0LSMIU\\SQLEXPRESS;Initial Catalog=asikyDB;Integrated Securit" +
            "y=True")]
        public string asikyDBConnectionString {
            get {
                return ((string)(this["asikyDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=70.32.28.3;Initial Catalog=DBasikyDemo;User ID=DbEssenDemo\n;Password=" +
            "Tb1wy~09")]
        public string asikyDBConnectionString1 {
            get {
                return ((string)(this["asikyDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SKSDLCB\\SQLEXPRESS;Initial Catalog=DBasikyDemo;Integrated Sec" +
            "urity=True")]
        public string DBasikyDemoConnectionString {
            get {
                return ((string)(this["DBasikyDemoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-38AJ5FV;Initial Catalog=DBasikyDemo;Integrated Security=True")]
        public string DBasikyDemoConnectionString1 {
            get {
                return ((string)(this["DBasikyDemoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-S3FML7B\\SQLEXPRESS;Initial Catalog=webkh_sushico; Integrated " +
            "Security = true")]
        public string webkh_sushicoConnectionString {
            get {
                return ((string)(this["webkh_sushicoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.101.161.16;Initial Catalog=webkh_sushico;User ID=webkh_sushico;Pa" +
            "ssword=s4pP45#q")]
        public string webkh_sushicoConnectionString1 {
            get {
                return ((string)(this["webkh_sushicoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-38AJ5FV\\MSSQLSERVER01;Initial Catalog=Db_daiviet;Integrated S" +
            "ecurity=True")]
        public string Db_daivietConnectionString {
            get {
                return ((string)(this["Db_daivietConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-38AJ5FV\\SQLEXPRESS;Initial Catalog=Db_daiviet;Integrated Secu" +
            "rity=True")]
        public string Db_daivietConnectionString1 {
            get {
                return ((string)(this["Db_daivietConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.101.161.16;Initial Catalog=webkh_dbdaiviet;User ID=webkh_dbdaivie" +
            "t;Password=D62?y7bp")]
        public string webkh_dbdaivietConnectionString {
            get {
                return ((string)(this["webkh_dbdaivietConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.226.248.52;Initial Catalog=webkhachhang_daiviet;User ID=webkhachh" +
            "ang_daiviet;Password=123456789a@@")]
        public string webkhachhang_daivietConnectionString {
            get {
                return ((string)(this["webkhachhang_daivietConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5LAGIRU\\MSSQLSERVER1;Initial Catalog=webkhachhang_daiviet;Int" +
            "egrated Security=True")]
        public string webkhachhang_daivietConnectionString1 {
            get {
                return ((string)(this["webkhachhang_daivietConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mi3-wsq5.my-hosting-panel.com;Initial Catalog=duccio_db;User ID=ducci" +
            "o_db;Password=123456789a@@")]
        public string duccio_dbConnectionString {
            get {
                return ((string)(this["duccio_dbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PMBV650\\SQLEXPRESS;Initial Catalog=hong_typer;Persist Securit" +
            "y Info=True;User ID=sa;Password=1234$")]
        public string hong_typerConnectionString {
            get {
                return ((string)(this["hong_typerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PMBV650\\SQLEXPRESS;Initial Catalog=hong_typer;User ID=sa;Pass" +
            "word=1234$")]
        public string hong_typerConnectionString1 {
            get {
                return ((string)(this["hong_typerConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.226.248.52;Initial Catalog=roadshine_db1;User ID=roadshine_db1;Pa" +
            "ssword=123456789a@@")]
        public string roadshine_db1ConnectionString {
            get {
                return ((string)(this["roadshine_db1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.226.248.52;Initial Catalog=roadshine_db1;Persist Security Info=Tr" +
            "ue;User ID=roadshine_db1;Password=123456789a@@")]
        public string roadshine_db1ConnectionString1 {
            get {
                return ((string)(this["roadshine_db1ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mi3-wsq5.my-hosting-panel.com;Initial Catalog=roadshine_db1;User ID=r" +
            "oadshine_db1;Password=123456789a@@")]
        public string roadshine_db1ConnectionString2 {
            get {
                return ((string)(this["roadshine_db1ConnectionString2"]));
            }
        }
    }
}
